import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://mietapa.etapa.net.ec/mi_etapa/hloginem.aspx")
    page.get_by_role("textbox", name="Usuario:").click()
    page.get_by_role("textbox", name="Usuario:").fill("0160049360001")
    page.get_by_role("textbox", name="Clave:").click()
    page.get_by_role("textbox", name="Clave:").fill("3st05$$esd#f1n4nc1r30")
    page.locator("iframe[name=\"a-x6a3hlji804n\"]").content_frame.get_by_role("checkbox", name="I'm not a robot").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"0\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"4\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"5\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"1\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"9\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"7\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"3\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"13\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.get_by_role("button", name="Next").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"14\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"15\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"11\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"13\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.locator("[id=\"10\"]").click()
    page.locator("iframe[name=\"c-x6a3hlji804n\"]").content_frame.get_by_role("button", name="Verify").click()
    page.get_by_role("button", name="INGRESAR").click()
    page.get_by_role("button", name="Nueva Orden").click()
    page.get_by_role("textbox", name="Nombre Usuario Ingresa *:").click()
    page.get_by_role("textbox", name="Nombre Usuario Ingresa *:").press("CapsLock")
    page.get_by_role("textbox", name="Nombre Usuario Ingresa *:").fill("ANITA")
    page.get_by_role("textbox", name="Nombre Usuario Ingresa *:").press("Tab")
    page.get_by_role("textbox", name="Apellido Usuario Ingresa *:").fill("ORELLANA")
    page.get_by_role("textbox", name="Apellido Usuario Ingresa *:").press("Tab")
    page.get_by_role("textbox", name="Nombre Institución *:").fill("EMOV EP")
    page.get_by_role("textbox", name="Nombre Institución *:").press("Tab")
    page.get_by_role("textbox", name="Cargo Usuario en Institución:").fill("ANALISTA CONTABILIDA")
    page.get_by_role("textbox", name="Cargo Usuario en Institución:").press("Tab")
    page.get_by_role("textbox", name="Teléfono:").fill("0983933527")
    page.get_by_role("button", name="Guardar").click()
    page.get_by_role("button", name="Regresar").click()
    page.get_by_role("img", name="hola").click()
    page.get_by_role("button", name="Agregar Deuda por Instalación").click()
    page.get_by_role("textbox", name="Instalación:").click()
    page.get_by_role("textbox", name="Instalación:").press("ControlOrMeta+V")
    page.get_by_role("textbox", name="Instalación:").fill("RDD01966")
    page.get_by_role("button", name="Consultar").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
